# Generated by Django 6.0.1 on 2026-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Librarian', 'Librarians'), ('Member', 'Member')], default='Member', max_length=20),
        ),
    ]
